name: Code quality
on: [push]

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 14
      - name: Install deps
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Typecheck
        run: yarn typecheck
